import os
import datetime

def get_time_greeting():
    """
    Returns a greeting message based on current KST time.
    """
    # UTC to KST (UTC+9)
    kst_now = datetime.datetime.utcnow() + datetime.timedelta(hours=9)
    hour = kst_now.hour
    
    greeting = ""
    
    if 6 <= hour < 9:
        greeting = "🌅 Good Morning! 커피부터 마시자."
    elif 9 <= hour < 12:
        greeting = "💻 오전 코딩 집중! (버그 심는 중?)"
    elif 12 <= hour < 13:
        greeting = "🍱 점심시간. 키보드에서 손 떼."
    elif 13 <= hour < 18:
        greeting = "☕ 오후의 홍차... 가 아니라 카페인 폭탄 필요."
    elif 18 <= hour < 20:
        greeting = "🏠 칼퇴 기원 (하지만 커밋은 하고 가야지?)"
    elif 20 <= hour < 23:
        greeting = "🌙 야간 코딩. 새벽 감성으로 코드 짜지 마라."
    elif 23 <= hour < 2:
        greeting = "🔥 Midnight Coding. 지금 자면 꿈을 꾸지만, 코딩하면 꿈을 이룬다."
    else:
        greeting = "🧟‍♂️ 새벽 3시 넘었다. 제발 좀 자라..."
        
    return f"""
<div align="center">
  <h3>⏰ {kst_now.strftime('%H:%M')} (KST) - {greeting}</h3>
</div>
<br/>
"""

def get_mood():
    """
    Simple placeholder for mood. Real logic handled by user activity or could be expanded.
    For now, static or random could be used, or removed if not needed.
    Currently just returns a simple divider or message.
    """
    return ""

def main():
    # Define the order of components
    components = [
        "header.md",
        "hud.md",
        "skills.md",
        "time_greeting",
        "web_status.md", # Generated by GitHub Actions Shell Script
        "snake.md",
        "chess.md",
        "meme.md",
        "weather.md",
        "minesweeper.md",
        "graph.md",
        "stats.md",
        "community.md"
    ]
    
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(current_dir)
    
    readme_content = ""
    
    print(f"Building README from {project_root}...")

    for component in components:
        if component == "time_greeting":
            readme_content += get_time_greeting() + "\n"
            print("Added Time Greeting")
            continue
            
        component_path = os.path.join(project_root, "components", component)
        
        if os.path.exists(component_path):
            with open(component_path, "r", encoding="utf-8") as f:
                readme_content += f.read() + "\n"
                print(f"Added {component}")
        else:
            # web_status.md might not exist locally, which is fine
            if component != "web_status.md":
                print(f"Warning: Component {component} not found at {component_path}")
            
    output_path = os.path.join(project_root, "readme.md")
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(readme_content)
    
    print(f"Successfully generated README.md at {output_path}")

if __name__ == "__main__":
    main()
